-- 1. Create the Storage Bucket for Media
INSERT INTO storage.buckets (id, name, public) 
VALUES ('songs', 'songs', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Set up Storage Policies (Allow public uploads/reads for your app)
CREATE POLICY "Allow public uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'songs');
CREATE POLICY "Allow public updates" ON storage.objects FOR UPDATE USING (bucket_id = 'songs');
CREATE POLICY "Allow public reads" ON storage.objects FOR SELECT USING (bucket_id = 'songs');
CREATE POLICY "Allow public deletes" ON storage.objects FOR DELETE USING (bucket_id = 'songs');

-- 3. Create the Database Table for your Content
CREATE TABLE IF NOT EXISTS public."AudioSongs" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic TEXT,
    language TEXT,
    tone TEXT,
    description TEXT,
    lyrics TEXT,
    audio_file TEXT,
    image_file TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Enable Security and Allow App Access to the Table
ALTER TABLE public."AudioSongs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public."AudioSongs" FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public."AudioSongs" FOR INSERT WITH CHECK (true);
